# Learn numpy.dot() function

In [2]:
import pandas as pd
import numpy as np

# two numbers

In [60]:
a = 1
b = 2
c = np.dot(a, b)
c

2

In [61]:
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'int'>
<class 'numpy.int32'>


# list & number 
=> result = array([1\*3, 2\*3])

In [49]:
a = [1,2]
b = 3
c = np.dot(a,b)
c

array([3, 6])

In [52]:
print(type(a))
print(type(b))
print(type(c))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>


# array & number 
=> result = array([1\*3, 2\*3])

In [62]:
a = np.array([1,2])
b = 3
c = np.dot(a,b)
c

array([3, 6])

In [63]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'int'>
<class 'numpy.ndarray'>


<!-- An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its shape, which is a tuple of N non-negative integers that specify the sizes of each dimension. The type of items in the array is specified by a separate data-type object (dtype), one of which is associated 
with each ndarray. -->

# two lists 
=> result: error 

In [79]:
a = [1,2]
b = [3]
c = np.dot(a,b)
c

ValueError: shapes (2,) and (1,) not aligned: 2 (dim 0) != 1 (dim 0)

In [76]:
print(type(a))
print(type(b))

<class 'list'>
<class 'list'>


# array & list
=> error

In [80]:
a = np.array([1,2])
b = [3]
c = np.dot(a,b)
c

ValueError: shapes (2,) and (1,) not aligned: 2 (dim 0) != 1 (dim 0)

In [81]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


# two lists
=> result: integer = 1\*3 + 2\*4 = 11

In [82]:
a = [1,2]
b = [3,4]
c = np.dot(a,b)
c

11

In [83]:
print(type(a))
print(type(b))
print(type(c))

<class 'list'>
<class 'list'>
<class 'numpy.int32'>


# two arrays

In [84]:
a = np.array([1,2])
b = np.array([3,4])
c = np.dot(a,b)
c

11

In [85]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int32'>


# two arrays 
=> result: integer = 0\*3 + 1\*4 + 2\*5 = 14

In [91]:
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.dot(a,b)
c

14

In [92]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int32'>


# two arrays
numpy.arange() function

In [108]:
a = np.arange(0,3)
b = np.arange(3,6)
c = np.dot(a,b)
print(a)
print(a.shape)
print(b)
print(b.shape)
print(c)

[0 1 2]
(3,)
[3 4 5]
(3,)
14


In [109]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int32'>


# two arrays
a array shape = 2 \* 3 matrix

b array shape = 3 \* 2 matrix

number of rows of a array = number of columns of b array

result: array ( \[ ∑ ( row * column ) \] )

In [111]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(3,2)
c = np.dot(a,b)
print(a)
print(a.shape)
print(b)
print(b.shape)
print(c)
print(c.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)
[[0 1]
 [2 3]
 [4 5]]
(3, 2)
[[10 13]
 [28 40]]
(2, 2)


In [112]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
